### ISSUE TITLE
Linux release is broken due to posix-incompatible paths

### ISSUE THREAD

**Issue by LorenzHetterich** [darkshoxx/Wheel#1]
Running the linux release will not find the required files since backwards slashes (\\) are used as path denominator instead of posix-complient forward slashes (/).

Since the audio file fails to load, clicking the wheel and trying to play it results in an exception:

```
java.lang.NullPointerException: Cannot invoke "com.jsyn.data.FloatSample.getNumFrames()" because "this.sample" is null
	at processing.sound.AudioSample.frames(Unknown Source)
	at processing.sound.SoundFile.frames(Unknown Source)
	at processing.sound.AudioSample.playInternal(Unknown Source)
	at processing.sound.AudioSample.play(Unknown Source)
	at processing.sound.SoundFile.play(Unknown Source)
	at WheelV1.draw(WheelV1.java:141)
	at processing.core.PApplet.handleDraw(PApplet.java:2094)
	at processing.awt.PSurfaceAWT$9.callDraw(PSurfaceAWT.java:1386)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:356)
```

Full output:
```
$ ./WheelV1 
Sound library error: unable to find file .\click_short.wav
The file ".\center1.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
The file ".\segments.txt" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
java.lang.NullPointerException: Cannot invoke "com.jsyn.data.FloatSample.getNumFrames()" because "this.sample" is null
	at processing.sound.AudioSample.frames(Unknown Source)
	at processing.sound.SoundFile.frames(Unknown Source)
	at processing.sound.AudioSample.playInternal(Unknown Source)
	at processing.sound.AudioSample.play(Unknown Source)
	at processing.sound.SoundFile.play(Unknown Source)
	at WheelV1.draw(WheelV1.java:141)
	at processing.core.PApplet.handleDraw(PApplet.java:2094)
	at processing.awt.PSurfaceAWT$9.callDraw(PSurfaceAWT.java:1386)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:356)
```

**Comment by darkshoxx** [comment]
Current Release 0.3.0 Should fix the paths issue. Please test when you have time. There was a sound issue on my Ubuntu, I'd appreciate feedback whether the tick sound plays or not (assuming that it runs :) )
